### ISSUE TITLE
BindMounts updated to Mounts

### ISSUE THREAD

**Issue by vyshnavcompass** [romnn/testcontainers#10]
In a recent updation of testcontainers, BindMounts in the ContainerRequest has been updated to Mounts.
Kindly review and fix
**From**: https://github.com/romnn/testcontainers/blob/c0e2a685eb012c415e05810fbd15a2519d75e397/kafka/kafka.go#L68
**To**: https://github.com/testcontainers/testcontainers-go/blob/41a9d3d94912d28abacca1f1eef353f454b9536a/container.go#L89

**Comment by romnn** [comment]
Dear @vyshnavcompass, thanks for bringing this up.

Excuse the late follow up, I have not been actively working on this. I just updated the dependencies and refactored the code, which should resolve this issue.

Best, Roman
