### ISSUE TITLE
Issue with module dependency

### ISSUE THREAD

**Issue by bvwells** [romnn/testcontainers#5]
This module pulls in a dependency on github.com/prometheus/common@v0.15.0 in the file

https://github.com/romnn/testcontainers/blob/c0e2a685eb012c415e05810fbd15a2519d75e397/log.go#L7

where it uses the log package.

This version of the dependency is quite out of date and the log package in github.com/prometheus/common is actually now deprecated (see https://github.com/prometheus/common/pull/306, https://github.com/prometheus/common/releases/tag/v0.27.0) 

This dependency causes some issues when using this module in a module which uses a more recent version of github.com/prometheus/common as go can't detect the correct module version of github.com/prometheus/common to use (due to the log package removal being a breaking change). Consumers end up with errors of the form:

```bash
> go mod tidy
....
        github.com/romnn/testcontainers imports
        github.com/prometheus/common/log: module github.com/prometheus/common@latest found (v0.32.1), but does not contain package github.com/prometheus/common/log
```

I looks like this dependency could be completely removed as it is only used to log an error. I wonder if the standard go log package would suffice here...

Happy to raise a PR if you think that this is a suitable solution.

**Comment by romnn** [comment]
Dear @bvwells, thanks for your contribution!

Excuse the late follow up, I have not been actively working on this. I just updated the dependencies and refactored the code, which should resolve this issue (only standard go logging is used).

Best, Roman
