### ISSUE TITLE
Checksum issue in mongo-driver v1.4.5

### ISSUE THREAD

**Issue by ilyakaznacheev** [romnn/testcontainers#8]
We ran into a problem when using the library because of a mongo-driver dependency with an invalid checksum.

The checksum problem is described here: https://jira.mongodb.org/projects/GODRIVER/issues/GODRIVER-1851?filter=allissues

To fix that they suggest bumping the version to 1.4.6.

**Comment by romnn** [comment]
closing as duplicate of PR #7
